# Generated by Django 5.1 on 2024-08-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='Product Images/'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='Product Images/'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='Product Images/'),
        ),
    ]
